### ISSUE TITLE
Back up drones with dio's best friends

### ISSUE THREAD

**Issue by DDDDxue** [BasilPanda/RoR2DronesInheritItems#1]
When a player has Dio's best friends in inventory, the back-up drones inherit this item of course, which leads to a resurrection after their destruction. 
However, the resurrected drones no longer have the 25 second time limits, which will not disappear unless the player proceed through the portal.

**Comment by BasilPanda** [comment]
I've decided to let the players decide to leave this in or not in the most recent update!

They can change the setting, InheritDio, in the config file to allow back-up drones to still inherit the item or not. 

At the moment, however, changing the setting to InheritDio will affect all other inheritable entities.
