### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by Solaire99** [BasilPanda/RoR2DronesInheritItems#11]
With the Drones Inherit Mods I have almost all drones unable to inherit items save for the TC280 prototype, equipment drone and the beetleguard. It works fine save for the missile drones which despite me labeling it false to have it not inherit items it still does.

**Comment by BasilPanda** [comment]
The mod probably wasn't updated at the time. It should be working now for the Anniversary Patch. Please let me know if it isn't!
