### ISSUE TITLE
Mod not working with "September2019 2.0 skills" update

### ISSUE THREAD

**Issue by aaforcebox** [BasilPanda/RoR2DronesInheritItems#3]
The mod not working with "September2019 2.0 skills" update. When you 'buy' a drone, the money is lost and the drone continues 'dead'.

**Comment by cclloyd** [comment]
I've noticed this applies to all drones.  It also applies to turrets, but unlike drones, you can rebuy and continue to waste your money on turrets after you fail to buy it the first time.

**Comment by BasilPanda** [comment]
Should be fixed in the most recent update!
