### ISSUE TITLE
Healing drones equipped with Visions of heresy Shoot at allies constantly. 

### ISSUE THREAD

**Issue by luna6667** [BasilPanda/RoR2DronesInheritItems#7]
As stated in the title, With how I'm assuming the healing drones heal, they end up constantly shooting allies with visions of heresy after picking up the item. This only happens with healing drones, as no other drone tries to "shoot" allies.

**Comment by BasilPanda** [comment]
I'll add a fix to blackmail this item specifically off healing drones.

**Comment by BasilPanda** [comment]
fixed in v2.4.12
