### ISSUE TITLE
Balance Suggestion: Blacklist Bustling Mushroom on Squid Turrets.

### ISSUE THREAD

**Issue by Omen267901** [BasilPanda/RoR2DronesInheritItems#8]
Squid Turrets with bustling mushroom are effectively invincible, and will never die over time. 

Also, is it intentional that all of the items a Squid turret has will awkwardly float around it?

**Comment by BasilPanda** [comment]
Not intentional but part of the default game design. You're free to use the custom blacklist to remove bustling mushroom specifically on Squid Turrets, however.
